# Constants for the XeThru Serial Protocol

# Protocol flags
XETHRU_START = 0x7d
XETHRU_END = 0x7e
XETHRU_ESC = 0x7f

# Identifiers
XTS_ID_APP_RESP = 0x1423a2d6
XTS_ID_APP_PRESENCE = 0x00288912
XTS_ID_RESP_STATUS = 0x2375fe26
XTS_ID_PRESENCE_STATUS = 0x991a52be
XTS_ID_DETECTION_ZONE = 0x96a10a1c

# Command codes
XTS_SPC_APPCOMMAND = 0x10
XTS_SPC_MOD_SETMODE = 0x20
XTS_SPC_MOD_LOADAPP = 0x21
XTS_SPC_MOD_RESET = 0x22

XTS_SPC_MOD_SETLEDCONTROL = 0x24

XTS_SPCA_SET = 0x10

XT_UI_LED_MODE_OFF = 0
XT_UI_LED_MODE_SIMPLE = 1
XT_UI_LED_MODE_FULL = 2

XTS_SM_RUN = 0x01
XTS_SM_IDLE = 0x11

# Response codes
XTS_SPR_ACK = 0x10
XTS_SPR_ERROR = 0x20
XTS_SPR_SYSTEM = 0x30
XTS_SPR_APPDATA = 0x50
XTS_SPRS_BOOTING = 0x10
XTS_SPRS_READY = 0x11

# Range limits
XETHRU_RESP_MIN = 0.5
XETHRU_RESP_MAX = 2.5
XETHRU_RESP_SPAN_MIN = 0.2
XETHRU_RESP_SPAN_MAX = 0.7

XETHRU_PRES_MIN = 0.5
XETHRU_PRES_MAX = 4.5
XETHRU_PRES_SPAN_MIN = 0.8
XETHRU_PRES_SPAN_MAX = 2.8

# Respiration application codes
XTS_VAL_RESP_STATE_BREATHING = 0
XTS_VAL_RESP_STATE_MOVEMENT = 1
XTS_VAL_RESP_STATE_MOVEMENT_TRACKING = 2
XTS_VAL_RESP_STATE_NO_MOVEMENT = 3
XTS_VAL_RESP_STATE_INTIALIZING = 4
XTS_VAL_RESP_STATE_RESERVED = 5
XTS_VAL_RESP_STATE_UNKNOWN = 6